#!/usr/bin/sh

# create user-dirs.dirs directories
# Add an extra check to see if we are in termux or not, as if we are, we will
# make links to android storage directories instead.
if [ -n "$TERMUX_VERSION" ] ; then
    if [ ! -r "/storage/emulated/0" ] ; then
        termux-setup-storage
        rm -fr ~/storage
    fi
    mkdir "$HOME/media"
    ln -s /storage/emulated/0 "$HOME/external"
    ln -s /storage/emulated/0/Download "$HOME/tmp"
    ln -s /storage/emulated/0/Documents "$HOME/docs"
    ln -s /storage/emulated/0/DCIM "$HOME/media/camera"
    ln -s /storage/emulated/0/Pictures "$HOME/media/image"
    ln -s /storage/emulated/0/Movies "$HOME/media/video"
    ln -s /storage/emulated/0/Music "$HOME/media/audio"
elif [ -f "$HOME/src/github.com/melonith/dotfiles/config/user-dirs.dirs" ] ; then
    tmp="$(mktemp)"

    grep -E '^XDG' "$HOME/src/github.com/melonith/dotfiles/config/user-dirs.dirs" | cut -d'=' -f 2 > "$tmp"

    for dir in $(cat $tmp); do
        eval mkdir -p "$dir"
    done

    rm -fr "$tmp"
fi

# link all files from dotfiles
# I assume the path because I always use this method for download repos.
rm -fr "$HOME/.bashrc" && ln -sf "$HOME/src/github.com/melonith/dotfiles/bashrc" "$HOME/.bashrc"
rm -fr "$HOME/.bash_profile" && ln -sf "$HOME/src/github.com/melonith/dotfiles/bash_profile" "$HOME/.bash_profile"
rm -fr "$HOME/.bash_logout" && ln -sf "$HOME/src/github.com/melonith/dotfiles/bash_logout" "$HOME/.bash_logout"
rm -fr "$HOME/.profile" && ln -sf "$HOME/src/github.com/melonith/dotfiles/profile" "$HOME/.profile"
rm -fr "$HOME/bin" && ln -sf "$HOME/src/github.com/melonith/dotfiles/bin" "$HOME/bin"
rm -fr "$HOME/.vimrc" && ln -sf "$HOME/src/github.com/melonith/dotfiles/vimrc" "$HOME/.vimrc"
rm -fr "$HOME/.inputrc" && ln -sf "$HOME/src/github.com/melonith/dotfiles/inputrc" "$HOME/.inputrc"

if [ ! -d "$HOME/.config" ] ; then
    mkdir -p "$HOME/.config"
fi

for f in $HOME/src/github.com/melonith/dotfiles/config/*; do
    ln -s $f $HOME/.config/
done
