set -g escape-time 5

set -g status-left-length 20
set-option -g detach-on-destroy off
set -g mouse on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf

bind-key -r a run-shell "tmux neww ~/bin/tmux-sessionizer"
bind-key -r f neww -c "#{pane_current_path}" "~/bin/tmux-file-selector"
bind-key -r M switch-client -t main

# Notes/Todo
bind-key -r I neww -c "#{pane_current_path}" "[ -e inbox.md ] && $EDITOR + inbox.md || $EDITOR + ~/notes/inbox.md"
bind-key -r N run-shell "~/bin/tmux-sessionizer ~/notes"
